/* Regenerate the self-hosted font set from the @fontsource packages.

   Copies the woff2 files this site actually needs into src/fonts/ and writes
   src/styles/fonts.css with @font-face rules that use the real family names — not
   @fontsource's "… Variable" aliases — so atlas.css and DESIGN.md §2 keep naming the same
   thing. Run after bumping a @fontsource dependency:  npm run fonts

   Only the latin and latin-ext subsets ship. The atlas has no content outside them, and
   unicode-range means a browser fetches latin-ext only if a page actually uses it. */
import fs from 'node:fs';
import path from 'node:path';

const NM = 'node_modules';
const KEEP = new Set(['latin', 'latin-ext']);
const OUT_CSS = 'src/styles/fonts.css';
const OUT_DIR = 'src/fonts';

/* [ source css, @fontsource family name, real family name ] — the css file's sibling
   files/ directory holds the woff2s it references. */
const SOURCES = [
  [`${NM}/@fontsource-variable/bricolage-grotesque/wght.css`, 'Bricolage Grotesque Variable', 'Bricolage Grotesque'],
  [`${NM}/@fontsource-variable/plus-jakarta-sans/wght.css`, 'Plus Jakarta Sans Variable', 'Plus Jakarta Sans'],
  ...[400, 500, 600].map(w => [`${NM}/@fontsource/ibm-plex-mono/${w}.css`, 'IBM Plex Mono', 'IBM Plex Mono']),
];

const HEADER = `/* Self-hosted web fonts — the three faces named in DESIGN.md §2.

   Generated by scripts/fonts.mjs from the @fontsource packages; the woff2 files live in
   src/fonts/ and Vite emits them hashed into /_astro/, which vercel.json already serves
   immutable. Only the latin and latin-ext subsets ship: the atlas has no content outside
   them, and unicode-range means a browser downloads latin-ext only if a page uses it.

   Family names are the real ones, not @fontsource's "… Variable" aliases, so atlas.css and
   DESIGN.md keep naming the same thing. Do not edit by hand — run \`npm run fonts\`. */
`;

fs.rmSync(OUT_DIR, { recursive: true, force: true });
fs.mkdirSync(OUT_DIR, { recursive: true });

const blocks = [HEADER];
let copied = 0;

for (const [cssPath, srcFamily, dstFamily] of SOURCES) {
  const css = fs.readFileSync(cssPath, 'utf8');
  const filesDir = path.join(path.dirname(cssPath), 'files');
  for (const [, name, face] of css.matchAll(/\/\* ([a-z0-9-]+) \*\/\s*(@font-face \{[^}]*\})/g)) {
    const subset = `-${name}-`.includes('-latin-ext-') ? 'latin-ext'
      : `-${name}-`.includes('-latin-') ? 'latin' : null;
    if (!KEEP.has(subset)) continue;

    const file = /url\(\.\/files\/([^)]+)\)/.exec(face)?.[1];
    if (!file) throw new Error(`no url() in ${name}`);
    fs.copyFileSync(path.join(filesDir, file), path.join(OUT_DIR, file));
    copied++;

    const rule = face
      .replace(`'${srcFamily}'`, `'${dstFamily}'`)
      .replace(`url(./files/${file})`, `url('../fonts/${file}')`)
      .replace(/\n\s*\n/g, '\n');
    blocks.push(`/* ${dstFamily} · ${subset} */\n${rule}\n`);
  }
}

fs.writeFileSync(OUT_CSS, blocks.join('\n'));
console.log(`${OUT_CSS}: ${blocks.length - 1} faces, ${copied} woff2 files in ${OUT_DIR}/`);
